### ISSUE TITLE
After creating concept in conceptpower, it does not show up in the search

### ISSUE THREAD

**Issue by jdamerow** [diging/vogon-web#205]
- I was searching for a concept when annotating a term but it did not exist yet
- I went to conceptpower and created the concept (J Presket Eckert)
- I went back to Vogon and searched for it
- I selected "Force fresh search"
- The concept does not show up in the search results

Expected bahavior: J Presket Eckert shows up in the search results after creating it in Conceptpower.

**Comment by nowke** [comment]
I cannot reproduce this issue. I am able to see the concepts added from Conceptpower, with the "Force fresh search" option immediately. 

I used latest `develop` branch for BE, and `master` branch for FE.
